add input validation (no cuda + macos) and shell variable

diff --git a/build-pymfem/action.yml b/build-pymfem/action.yml
--- a/build-pymfem/action.yml
+++ b/build-pymfem/action.yml
@@ -62,13 +62,24 @@ runs:
   # -------------------------------------------------------------------------------------------------
   # Setup / config
   # -------------------------------------------------------------------------------------------------
+  - name: Validate inputs
+    run: |
+      if [[ "${{ inputs.os }}" == "macos-latest" && "${{ inputs.cuda }}" == "true" ]]; then
+        echo "Error: CUDA is not supported on macOS"
+        exit 1
+      fi
+    shell: bash
+
   - name: Checkout repo
     uses: actions/checkout@v4
+    shell: bash
 
   - name: Set up Python ${{ inputs.python-version }}
     uses: actions/setup-python@v5
     with:
       python-version: ${{ inputs.python-version }}
+    shell: bash
+
   # Reference for $${{ x && y || z }} syntax: https://7tonshark.com/posts/github-actions-ternary-operator/
   - name: Set build flags
     # These are all passed to setup.py as one concatenated string
@@ -78,18 +89,21 @@ runs:
       ${{ inputs.libceed && '--with-libceed' || '' }} \
       ${{ inputs.gslib && '--with-gslib' || '' }} \
       ${{ (!(inputs.mfem-branch == 'default') && format('--mfem-branch=''{0}''', inputs.mfem-branch)) || '' }}" >> $GITHUB_ENV
+    shell: bash
 
   # -------------------------------------------------------------------------------------------------
   # Download/install dependencies
   # -------------------------------------------------------------------------------------------------
   - name: Install core dependencies via requirements.txt
     run: pip install -r requirements.txt --verbose
+    shell: bash
 
   - name: Install MPI
     if: inputs.parallel
     run: |
       sudo apt-get install mpich libmpich-dev
       pip install mpi4py
+    shell: bash
 
   - name: Cache CUDA
     if: inputs.cuda
@@ -98,12 +112,14 @@ runs:
     with:
       path: ~/cache
       key: cuda-installer-${{ env.cuda-toolkit-version }}-${{ env.cuda-driver-version }}
+    shell: bash
 
   - name: Download CUDA
     if: inputs.cuda && steps.cache-cuda.outputs.cache-hit == false
     run: |
       CUDA_URL="https://developer.download.nvidia.com/compute/cuda/${{ env.cuda-toolkit-version }}/local_installers/cuda_${{ env.cuda-toolkit-version }}_${{ env.cuda-driver-version }}_linux.run"
       curl -o ~/cache/cuda.run --create-dirs $CUDA_URL
+    shell: bash
 
   - name: Install CUDA
     if: inputs.cuda
@@ -111,6 +127,7 @@ runs:
       # The --silent flag is necessary to bypass user-input, e.g. accepting the EULA
       sudo sh ~/cache/cuda.run --silent --toolkit
       echo "/usr/local/cuda/bin" >> $GITHUB_PATH
+    shell: bash
 
   - name: Print dependency information
     run: |
@@ -119,6 +136,7 @@ runs:
       mpiexec --version || printf "MPI not installed"
       printf "\n\n---------- CUDA ----------\n"
       nvcc --version || printf "CUDA not installed"
+    shell: bash
 
   # -------------------------------------------------------------------------------------------------
   # Build MFEM + SWIG Bindings + PyMFEM
@@ -127,18 +145,22 @@ runs:
   - name: Build MFEM (step 1)
     if: inputs.phases
     run: python setup.py install --ext-only --vv ${{ env.BUILD-FLAGS }}
+    shell: bash
 
   - name: Build SWIG wrappers (step 2)
     if: inputs.phases
     run: python setup.py install --swig --vv ${{ env.BUILD-FLAGS }}
+    shell: bash
 
   - name: Build PyMFEM (step 3)
     if: inputs.phases
     run: python setup.py install --skip-ext --skip-swig --vv ${{ env.BUILD-FLAGS }}
+    shell: bash
 
   - name: Build all (steps 1-3)
     if: inputs.phases == false
     run: python setup.py install --vv ${{ env.BUILD-FLAGS }}
+    shell: bash
 
   # -------------------------------------------------------------------------------------------------
   # Run tests
@@ -148,12 +170,14 @@ runs:
     run: |
       cd test
       python run_examples.py -serial -verbose
+    shell: bash
 
   - name: Run tests (parallel)
     if: inputs.parallel
     run: |
       cd test
       python run_examples.py -parallel -verbose -np 2
+    shell: bash
 
   # -------------------------------------------------------------------------------------------------
   # Generate an artifact (output of tests) on failure
@@ -165,6 +189,7 @@ runs:
       # generate a name for the artifact
       txt=$(python -c "import datetime;print(datetime.datetime.now().strftime('%H_%M_%S_%f'))")
       echo name="test_results_"${txt}"_"${{ github.run_id }}".tar.gz" >> $GITHUB_OUTPUT
+    shell: bash
 
   - name: Upload Artifact
     uses: actions/upload-artifact@v4
@@ -173,3 +198,4 @@ runs:
         name: ${{ steps.generate-artifact.outputs.name }}
         path: sandbox.tar.gz
         retention-days: 1
+    shell: bash
